BROKER_URL = 'redis://'
# ELERY_ENABLE_UTC = True
# CELERY_TIMEZONE = 'UTC'

CELERYBEAT_SCHEDULER = 'redisbeater.RedisBeaterScheduler'
CELERYBEAT_MAX_LOOP_INTERVAL = 5  # redisbeater likes fast loops

# REDISBEATER_REDIS_URL = BROKER_URL
# REDISBEATER_KEY_PREFIX = 'redisbeater'
# REDISBEATER_SCHEDULE_KEY = REDISBEATER_KEY_PREFIX + ':schedule'
# REDISBEATER_STATICS_KEY = REDISBEATER_KEY_PREFIX + ':statics'
# REDISBEATER_LOCK_KEY = REDISBEATER_KEY_PREFIX + ':lock'
# REDISBEATER_LOCK_TIMEOUT = CELERYBEAT_MAX_LOOP_INTERVAL * 5
